<?php 
/*
Plugin Name: ProductMaker
Plugin URI: nimra-tech.com/myplugin
Description: ProductMaker is used for making finished product by using selecting various row materials.
Version: 0.0.1
Author: Shajeeb S
Author URI: nimra-tech.com
Text Domain: p
Generated By: http://nimra-tech.com
*/

add_action('admin_menu', 'addAdminProductMakerPage');
function addAdminProductMakerPage() {
  add_menu_page('Product Maker', 'Product Maker', 'manage_options' ,__FILE__, 'productMakerAdminPage', 'dashicons-wordpress');
}
function productMakerAdminPage() {
  global $wpdb;
  $table_name = $wpdb->prefix . 'erp_acct_products';
  if (isset($_POST['newsubmit'])) {
    $name = $_POST['name'];
    $email = $_POST['product_type_id'];
    $product_type_id = $_POST['product_type_id'];
    $category_id = $_POST['category_id'];
    $tax_cat_id = $_POST['tax_cat_id'];
    $vendor = $_POST['vendor'];
    $cost_price = $_POST['cost_price'];
    $sale_price = $_POST['sale_price'];
    $wpdb->query("INSERT INTO $table_name(name,product_type_id,category_id,tax_cat_id,vendor,cost_price,sale_price) VALUES('$name',$product_type_id,$category_id,$tax_cat_id,$vendor,$cost_price,$sale_price)");
    echo "<script>location.replace('admin.php?page=crud.php');</script>";
  }
  if (isset($_POST['uptsubmit'])) {
    $id = $_POST['uptid'];
    $name = $_POST['uptname'];
    $product_type_id = $_POST['uptproduct_type_id'];
    $category_id = $_POST['uptcategory_id'];
    $tax_cat_id = $_POST['upttax_cat_id'];
    $vendor = $_POST['uptvendor'];
    $cost_price = $_POST['uptcost_price'];
    $sale_price = $_POST['uptsale_price'];
    $wpdb->query("UPDATE $table_name SET name='$name',product_type_id='$product_type_id',category_id='$category_id',tax_cat_id='$tax_cat_id',vendor='$vendor',cost_price='$cost_price',sale_price='$sale_price' WHERE id='$id'");
    echo "<script>location.replace('admin.php?page=crud.php');</script>";
  }
  if (isset($_GET['del'])) {
    $del_id = $_GET['del'];
    $wpdb->query("DELETE FROM $table_name WHERE id='$del_id'");
    echo "<script>location.replace('admin.php?page=crud.php');</script>";
  }
  ?>
  <div class="wrap">
    <h2>Product Maker</h2>
    <h4>Makes finished goods by converting raw materials</h4>
    <table class="wp-list-table widefat striped">
      <thead>
        <tr>
          <th width="20%">Product ID</th>
          <th width="25%">Product Name</th>
          <th width="20%">Product Type</th>
          <th width="20%">Category</th>
          <th width="20%">Tax Category</th>
          <th width="20%">Vendor</th>
          <th width="5%">Cost Price</th>
          <th width="5%">Sale Price</th>
          <th width="25%">Actions</th>
        </tr>
      </thead>
      <tbody>
        <form action="" method="post">
          <tr>
            <td><input type="text" value="AUTO_GENERATED" disabled></td>
            <td><input type="text" id="name" name="name"></td>
            <td><input type="text" id="product_type_id" name="product_type_id"></td>
            <td><input type="text" id="category_id" name="category_id"></td>
            <td><input type="text" id="tax_cat_id" name="tax_cat_id"></td>
            <td><input type="text" id="vendor" name="vendor"></td>
            <td><input type="text" id="cost_price" name="cost_price"></td>
            <td><input type="text" id="sale_price" name="sale_price"></td>
            <td><button id="newsubmit" name="newsubmit" type="submit">INSERT</button></td>
          </tr>
        </form>
        <?php
          $result = $wpdb->get_results("SELECT * FROM $table_name");
          foreach ($result as $print) {
            echo "
              <tr>
                <td width='20%'>$print->id</td>
                <td width='25%'>$print->name</td>
                <td width='20%'>$print->product_type_id</td>
                <td width='20%'>$print->category_id</td>
                <td width='20%'>$print->tax_cat_id</td>
                <td width='20%'>$print->vendor</td>
                <td width='5%'>$print->cost_price</td>
                <td width='5%'>$print->sale_price</td>
                <td width='25%'><a href='admin.php?page=crud.php&upt=$print->id'><button type='button'>UPDATE</button></a> <a href='admin.php?page=crud.php&del=$print->id'><button type='button'>DELETE</button></a></td>
              </tr>
            ";
          }
        ?>
      </tbody>  
    </table>
    <br>
    <br>
    <?php
      if (isset($_GET['upt'])) {
        $upt_id = $_GET['upt'];
        $result = $wpdb->get_results("SELECT * FROM $table_name WHERE id='$upt_id'");
        foreach($result as $print) {
          $name = $print->name;
          $email = $print->product_type_id;
          $email = $print->category_id;
          $email = $print->tax_cat_id;
          $email = $print->vendor;
          $email = $print->cost_price;
          $email = $print->sale_price;
        }
        echo "
        <table class='wp-list-table widefat striped'>
          <thead>
            <tr>
                <th width='20%'>Product ID</th>
                <th width='25%'>Product Name</th>
                <th width='20%'>Product Type</th>
                <th width='20%'>Category</th>
                <th width='20%'>Tax Category</th>
                <th width='20%'>Vendor</th>
                <th width='5%'>Cost Price</th>
                <th width='5%'>Sale Price</th>
                <th width='25%'>Actions</th>
            </tr>
          </thead>
          <tbody>
            <form action='' method='post'>
              <tr>
                <td width='25%'>$print->id <input type='hidden' id='uptid' name='uptid' value='$print->id'></td>
                <td width='25%'><input type='text' id='uptname' name='uptname' value='$print->name'></td>
                <td width='25%'><input type='text' id='uptproduct_type_id' name='uptproduct_type_id' value='$print->product_type_id'></td>
                <td width='25%'><input type='text' id='uptcategory_id' name='uptcategory_id' value='$print->category_id'></td>
                <td width='25%'><input type='text' id='upttax_cat_id' name='upttax_cat_id' value='$print->tax_cat_id'></td>
                <td width='25%'><input type='text' id='uptvendor' name='uptvendor' value='$print->vendor'></td>
                <td width='25%'><input type='text' id='uptcost_price' name='uptcost_price' value='$print->cost_price'></td>
                <td width='25%'><input type='text' id='uptsale_price' name='uptsale_price' value='$print->sale_price'></td>
                <td width='25%'><button id='uptsubmit' name='uptsubmit' type='submit'>UPDATE</button> <a href='admin.php?page=crud.php'><button type='button'>CANCEL</button></a></td>
              </tr>
            </form>
          </tbody>
        </table>";
      }
    ?>
  </div>
  <?php
}