<?php 
/*
Plugin Name: RunTests
Plugin URI: nimra-tech.com/myplugin
Description: This module is used for testing different functionalities.
Version: 0.0.1
Author: Shajeeb S
Author URI: 
Text Domain: p
Generated By: 
*/

add_action('admin_menu', 'addAdminRunTestPage');
function addAdminRunTestPage() {
  add_menu_page('Run Tests', 'Run Tests', 'manage_options' ,__FILE__, 'runTestsAdminPage', 'dashicons-wordpress');
}

function runTestsAdminPage() {
  global $wpdb;?>
  <div class="wrap">
    <h2>Run Tests</h2>
    <h4>This module is used for testing different functionalities</h4>
    <div class="rowLayout">		
      <div class="columnLayout" style="background-color:#74cfd27a;">
        <p>Test erp_acct_get_vendor_products()</p>
           <?php 
            require_once(ABSPATH . 'wp-content\plugins\erp\modules\accounting\includes\functions\products.php');
            $returnArray['prodTypes'] = erp_acct_get_product_types();
            $vendorProds = erp_acct_get_vendor_products(array('count' => false, 'number'=>-1));
            print('vendorProds');
            print_r($vendorProds);
            ?>
        
      </div>
      <div class="columnLayout" style="background-color:#f1caca;">
        <p></p>
      </div>
    </div>
  </div>
  <?php
}?>